version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/production
    ports:
      - "80:3000"
    environment:
        PORT: "3000"
        PGHOST: "db"
        PGUSER: "postgres"
        PGDBNAME: "production"
    depends_on:
      - db
