version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server"
    volumes:
      - .:/cvwo
    ports:
            - "80:3000"
    depends_on:
      - db
